import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar";
import AuthContext from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex flex-col w-full h-screen">
        <AuthContext>
          <Navbar />
          <main className="flex-1 w-full h-full">{children}</main>
        </AuthContext>
      </body>
    </html>
  );
}
